export const trendingCollection = [
  {
    id: 1,
    title: "DEGN Animals",
    images: [
      "/images/trending/1.png",
      "/images/trending/2.png",
      "/images/trending/3.png",
    ],
    totalItem: 1025,
    userName: "MRFox",
    avatar: "/images/top-creators/6.png",
  },
  {
    id: 2,
    title: "Magic Mushrooms",
    images: [
      "/images/trending/4.png",
      "/images/trending/4.png",
      "/images/trending/4.png",
    ],
    totalItem: 725,
    userName: "Shroomie",
    avatar: "/images/top-creators/7.png",
  },
  {
    id: 3,
    title: "Disco Machines",
    images: [
      "/images/trending/5.png",
      "/images/trending/6.png",
      "/images/trending/7.png",
    ],
    totalItem: 1300,
    userName: "BeKind2Robots",
    avatar: "/images/top-creators/4.png",
  },
];

export const salesDetails = [
  {
    id: 1,
    title: "Total Sale",
    amount: 240,
  },
  {
    id: 2,
    title: "Auctions",
    amount: 100,
  },
  {
    id: 3,
    title: "Artists",
    amount: 240,
  },
];

export const workFlow = [
  {
    id: 1,
    title: "Setup Your wallet",
    description:
      "Set up your wallet of choice. Connect it to the Animarket by clicking the wallet icon in the top right corner.",
    imgUrl: "/images/workflow/1.png",
  },
  {
    id: 2,
    title: "Create Collection",
    description:
      "Upload your work and setup your collection. Add a description, social links and floor price.",
    imgUrl: "/images/workflow/2.png",
  },
  {
    id: 3,
    title: "Start Earning",
    description:
      "Choose between auctions and fixed-price listings. Start earning by selling your NFTs or trading others.",
    imgUrl: "/images/workflow/3.png",
  },
];

export const Categories = [
  {
    id: 1,
    title: "Art",
    bgImageUrl: "/images/categories/1.png",
    iconImageUrl: "/images/categoryIcons/1.png",
  },
  {
    id: 2,
    title: "Collectibles",
    bgImageUrl: "/images/categories/2.png",
    iconImageUrl: "/images/categoryIcons/2.png",
  },
  {
    id: 3,
    title: "Music",
    bgImageUrl: "/images/categories/3.png",
    iconImageUrl: "/images/categoryIcons/3.png",
  },
  {
    id: 4,
    title: "Photography",
    bgImageUrl: "/images/categories/4.png",
    iconImageUrl: "/images/categoryIcons/4.png",
  },
  {
    id: 5,
    title: "Video",
    bgImageUrl: "/images/categories/5.png",
    iconImageUrl: "/images/categoryIcons/5.png",
  },
  {
    id: 6,
    title: "Utility",
    bgImageUrl: "/images/categories/6.png",
    iconImageUrl: "/images/categoryIcons/6.png",
  },
  {
    id: 7,
    title: "Sport",
    bgImageUrl: "/images/categories/7.png",
    iconImageUrl: "/images/categoryIcons/7.png",
  },
  {
    id: 8,
    title: "Virtual Worlds",
    bgImageUrl: "/images/categories/8.png",
    iconImageUrl: "/images/categoryIcons/8.png",
  },
];

export const topCreators = [
  {
    id: 1,
    creatorName: "Ruben Carder",
    avatar: "/images/top-creators/1.png",
    change: 1.41,
    totalSales: 12.4,
    nftSold: 602,
  },
  {
    id: 2,
    creatorName: "Alice Smith",
    avatar: "/images/top-creators/2.png",
    change: -0.32,
    totalSales: 8.7,
    nftSold: 420,
  },
  {
    id: 3,
    creatorName: "John Doe",
    avatar: "/images/top-creators/3.png",
    change: 0.75,
    totalSales: 9.2,
    nftSold: 310,
  },
  {
    id: 4,
    creatorName: "Emma Johnson",
    avatar: "/images/top-creators/4.png",
    change: -0.92,
    totalSales: 5.6,
    nftSold: 180,
  },
  {
    id: 5,
    creatorName: "David Brown",
    avatar: "/images/top-creators/5.png",
    change: 0.21,
    totalSales: 14.8,
    nftSold: 720,
  },
  {
    id: 6,
    creatorName: "Sophia Wilson",
    avatar: "/images/top-creators/6.png",
    change: 1.03,
    totalSales: 17.2,
    nftSold: 920,
  },
  {
    id: 7,
    creatorName: "Michael Garcia",
    avatar: "/images/top-creators/7.png",
    change: -0.15,
    totalSales: 11.1,
    nftSold: 540,
  },
  {
    id: 8,
    creatorName: "Olivia Taylor",
    avatar: "/images/top-creators/8.png",
    change: 0.64,
    totalSales: 6.9,
    nftSold: 260,
  },
  {
    id: 9,
    creatorName: "William Anderson",
    avatar: "/images/top-creators/9.png",
    change: -0.82,
    totalSales: 3.5,
    nftSold: 130,
  },
  {
    id: 10,
    creatorName: "Ava Martinez",
    avatar: "/images/top-creators/10.png",
    change: 0.96,
    totalSales: 10.5,
    nftSold: 450,
  },
  {
    id: 11,
    creatorName: "James Jackson",
    avatar: "/images/top-creators/11.png",
    change: -0.43,
    totalSales: 7.8,
    nftSold: 380,
  },
  {
    id: 12,
    creatorName: "Isabella Brown",
    avatar: "/images/top-creators/12.png",
    change: 0.51,
    totalSales: 13.7,
    nftSold: 680,
  },
  {
    id: 13,
    creatorName: "Logan Thomas",
    avatar: "/images/top-creators/1.png",
    change: 1.12,
    totalSales: 16.3,
    nftSold: 780,
  },
  {
    id: 14,
    creatorName: "Mia White",
    avatar: "/images/top-creators/2.png",
    change: -0.27,
    totalSales: 8.1,
    nftSold: 390,
  },
  {
    id: 15,
    creatorName: "Benjamin Davis",
    avatar: "/images/top-creators/3.png",
    change: 0.37,
    totalSales: 11.9,
    nftSold: 570,
  },
  {
    id: 16,
    creatorName: "Charlotte Rodriguez",
    avatar: "/images/top-creators/4.png",
    change: -0.63,
    totalSales: 4.4,
    nftSold: 210,
  },
  {
    id: 17,
    creatorName: "Daniel Lopez",
    avatar: "/images/top-creators/5.png",
    change: 0.81,
    totalSales: 9.8,
    nftSold: 470,
  },
  {
    id: 18,
    creatorName: "Emily Garcia",
    avatar: "/images/top-creators/6.png",
    change: -0.18,
    totalSales: 6.2,
    nftSold: 290,
  },
  {
    id: 19,
    creatorName: "Ethan Martinez",
    avatar: "/images/top-creators/7.png",
    change: 0.69,
    totalSales: 7.5,
    nftSold: 360,
  },
  {
    id: 20,
    creatorName: "Elena Martinez",
    avatar: "/images/top-creators/8.png",
    change: 0.76,
    totalSales: 15.9,
    nftSold: 820,
  },
];

export const moreNfts = [
  {
    id: 1,
    title: "Distant Galaxy",
    name: "MoonDancer",
    price: 1.63,
    bid: 0.33,
    image: "/images/more-nft/1.png",
    avatar: "/images/top-creators/1.png",
  },
  {
    id: 2,
    title: "Life On Edena",
    name: "Nebulakid",
    price: 1.63,
    bid: 0.33,
    image: "/images/more-nft/2.png",
    avatar: "/images/top-creators/2.png",
  },
  {
    id: 3,
    title: "AstroFiction",
    name: "Spaceone",
    price: 1.63,
    bid: 0.33,
    image: "/images/more-nft/3.png",
    avatar: "/images/top-creators/3.png",
  },
  {
    id: 4,
    title: "Stellar Dreams",
    name: "StarSeeker",
    price: 2.1,
    bid: 0.45,
    image: "/images/more-nft/4.png",
    avatar: "/images/top-creators/4.png",
  },
  {
    id: 5,
    title: "Cosmic Odyssey",
    name: "GalaxyGazer",
    price: 2.25,
    bid: 0.5,
    image: "/images/more-nft/5.png",
    avatar: "/images/top-creators/5.png",
  },
  {
    id: 6,
    title: "Nebula Whispers",
    name: "StarryWhisperer",
    price: 1.8,
    bid: 0.4,
    image: "/images/more-nft/6.png",
    avatar: "/images/top-creators/6.png",
  },
  {
    id: 7,
    title: "Celestial Serenity",
    name: "SkySerenader",
    price: 2.0,
    bid: 0.35,
    image: "/images/more-nft/7.png",
    avatar: "/images/top-creators/7.png",
  },
  {
    id: 8,
    title: "Galactic Rhapsody",
    name: "StarSymphony",
    price: 1.95,
    bid: 0.38,
    image: "/images/more-nft/8.png",
    avatar: "/images/top-creators/8.png",
  },
  {
    id: 9,
    title: "Astral Harmony",
    name: "CosmicComposer",
    price: 2.2,
    bid: 0.48,
    image: "/images/more-nft/9.png",
    avatar: "/images/top-creators/9.png",
  },
  {
    id: 10,
    title: "Lunar Whimsy",
    name: "StarDreamer",
    price: 1.75,
    bid: 0.3,
    image: "/images/more-nft/10.png",
    avatar: "/images/top-creators/10.png",
  },
  {
    id: 11,
    title: "Space Reverie",
    name: "AstroSoul",
    price: 2.05,
    bid: 0.42,
    image: "/images/more-nft/11.png",
    avatar: "/images/top-creators/11.png",
  },
  {
    id: 12,
    title: "Nebula Dreamscape",
    name: "StellarVoyager",
    price: 2.15,
    bid: 0.47,
    image: "/images/more-nft/12.png",
    avatar: "/images/top-creators/12.png",
  },
];
